server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://192.168.254.154:3306/taskdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root        # 你的 MySQL 用户名
    password: 123456      # 你的 MySQL 密码
  jpa:
    hibernate:
      ddl-auto: update    # 自动建表（开发环境）
    show-sql: true        # 控制台输出 SQL
    properties:
      hibernate:
        format_sql: true  # 格式化 SQL